### PR TITLE
#329/fix unread

### LINKED ISSUE #329: Unread messages not being flagged in `ConversationCard.tsx`
### Description of the Bug

In our seed data there is a message unread for each of the test users in separate conversations. 

When we first start the environment we can see the notification dot over the button linking to `/conversations` but once we navigate to that route the notification is not showing in the appropriate conversation.

From `/`
Image

From `/conversations`
Image

Similarly, if you send a new message and then log in as the other user you can see that the `/conversations` link shows a notification dot but the relevant `ConversationCard.tsx` does not.

### What should happen instead

The conversation that previews "Unread to refugee" should be marked as unread when you are logged in as the refugee. The same should happen with the last conversation on the list when you log in as the donor.

**Note:**
Marking a conversation as unread by clicking the dropdown menu on the `ConversationCard.tsx` still works as expected.
Image

### Steps to reproduce this bug

1. `npx supabase db reset` if you have been interacting with the data before this
2. start the application
3. log in as the test refugee or test donor
4. visit the `/conversations` route
5. you should see one of the conversations highlighted with a notification dot, but you don't right now

### What could we do to solve this bug?

`ConversationsList.tsx` sets a state that is intended to map through the list of all conversations and map out an array of the `conversation_id` value of each conversation that has notifications (check the database schema for this). That list is passed down to the `ConversationCard.tsx` to allow an evaluation that decides whether the notification dot should be showing.

This at least is how it was working before, but that logic seems to have been lost maybe in a merge.

The solution may look different now, but will surely need touching those files.

🧪 This will need some E2E tests being added to avoid further regression. Cypress is still frighteningly blind to our messaging right now.

### Assignment

This issue is free for anyone to take

### PR DESCRIPTION
**Pull request by camelPhonso**
# Description

**Closes #329**  

Bug fix for displaying a notification dot over any conversation card to a conversation with unread messages.

Extended tests to our messaging feature to avoid regression.

### Files changed

- `supabase/migrations/20240906121523_**.sql` - new migration file recreating the `fetch_user_conversations` function in our database to return the value of `has_unread_messages` in each conversation
- `ConversationsList.tsx` - added useEffect to update `notificationsList` local state when changes occur to `allConversations` in the wider context.
- `components/messaging/**.tsx` && `app/styles/messaging-styltes.css` - lifted some stylings and added `name` attributes to some elements for testability of the messaging functionality
- `messaging.cy.js`, `URLS.json` && `conversationsPage.js`- new testing suite for messaging feature

### UI changes

none - everything looks the same as before the bug was introduced

### Changes to Documentation

none

# Tests

New test suite verifies that:
 - users can see a notification dot for any conversations with unread messages
 - clicking a conversation removes the notification dot from it
 - a conversation can be marked as unread via the ellipsis button on the conversation card
 - a conversation can be deleted via the ellipsis button on the conversation card
 - a new message can be sent and will be immediately displayed on the page

### CODE REVIEW

**Review by ShaughnAnderson94 — APPROVED** [review]
some notes on old junk computers a lot of tests are failing and I am having to manually check (visit about page, the before each for search, item test body and the reservation test

in addition its worth checking that its not just me but all the images on messages are broken 
image

If you can confirm thats just old computer on bad internet then you can merge

**Comment by ShaughnAnderson94** [comment]
@camelPhonso 
I cant see any dots 
image
and this test fails
image

**Comment by camelPhonso** [comment]
> this test fails image

🤔 I had the same until I ran `npx supabase db reset` and then it behaved normal.

Screenshot 2024-09-23 at 09 25 33

Screenshot 2024-09-23 at 09 25 44

**Review by ShaughnAnderson94 — APPROVED** [review]
sorted out those errors looks like they were coming from my end anyways 😅 youre good to go

**Pull request merged**
