### PR TITLE
#69/mark conversation unread

### LINKED ISSUE #69: Mark conversation as unread
- Implement ‘mark all as unread’ feature (accessible via three dot menu)
- Meatball menu to be displayed on the top-right corner of ConversationCards

Image

### PR DESCRIPTION
**Pull request by camelPhonso**
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review on my code
- [x] I have made corresponding changes to the documentation (if any were needed)
- [x] My changes generate no new warnings or errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and previously existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# Description

**Closes #69**  
**Relates #169**

In solving issue #69 I first tried to trigger a function already in use in our codebase by introducing a system message into all conversations at the start. This ended up not being the approach needed _however_ it is a common practice and it helps us reflect in the UI that a new conversation is being retrieved (instead of the page simply being empty). 

Because this solution is pertinent to issue #169 I have kept those changes in this PR and will submit in a new PR a few extra adjustments if this is approved to add a new system message onto all relevant conversations when an Item is deleted.

### Files changed

- `insertSystemMessage.ts` - new util that will enter a message onto any given conversation under the system user "trafalgargirls". This can be used for any notifications necessary in a conversation
- `NewConversationButton.tsx` - added a callback to my new util `insertSystemMessage`
- `ConversationCardModal.tsx` - added a handler function for marking conversations as unread
- `updateConversationReadStatus.ts` - new util that will toggle the `has_unread_messages` property of a given conversation
- `ConversationsList.tsx` - added a callback to `updateConversationReadStatus.ts` to mark a conversation as read when it is opened
- `SystemMessageCard.tsx` - new component to display messages within a conversation that were sent by the system user 'trafalgargirls'
- `CurrentConversation.tsx` - conditionally rendering `MessageCard.tsx` or `SystemMessageCard.tsx` based on the `sender_id` of each message
- `selectSystemUser.ts` - new util that retrieves the Id of the system user "trafalgargirls"
- `newConvoStart.ts` - renamed `startNewConversationStart.ts` to fit our conventions

### UI changes

New conversations will now display a `SystemMessageCard.tsx` confirming the start of the conversation.

Screenshot 2024-05-22 at 11 02 24

When marked as 'unread' conversations are flagged as before.

### Changes to Documentation

No changes to documentation needed for this feature :)

# Tests

Include a description of any tests added - if none have been added explain why.

### CODE REVIEW

**Comment by eliazzo** [comment]
It's not really a bug and potentially even a separate issue, but the modal menu only closes when you re-click the three dots (which are sometimes partially covered). I think typically the modal would automatically close when the user clicks 'mark conversation as unread'

Screenshot 2024-05-22 at 17 15 35
Screenshot 2024-05-22 at 17 18 14

**Comment by camelPhonso** [comment]
> Love the tidying of file/ variable names 👌 One small comment on the naming convention...for messaging util functions we are using `select` eg `selectSystemUser`, but the other util functions use `get` eg `getProfiles`. I personally prefer `get` but it's not an urgent change

I did notice this. All the models from the original build use `get` but all the messaging models use `select` because I think we actually put that on the conventions in our documentation - select emulates the sql command so it indicates this is a model for a database call. Part of me was aching to just change all the old ones actually, but that would make the PR unnecessarily large 😅 

> It's not really a bug and potentially even a separate issue, but the modal menu only closes when you re-click the three dots (which are sometimes partially covered). I think typically the modal would automatically close when the user clicks 'mark unread'

Yes, I actually spent a little time on getting the modal to close immediately but could not get to it. My thinking is to create a new issue as a 'bug fix' (though it doesn't break the code, it's just not the best UX) since it's a behaviour the modal has already on the dev. It originally looked to me like it would be a really simple fix but for some reason it wasn't working that easily.

I could spend a little longer on it and add to this PR if you think that's a better way about it - since I'm already working mostly on that file it shouldn't bulk up the PR

**Comment by eliazzo** [comment]
We can make a separate issue for the renaming the util functions? Re the modal window, it's up to you. We can make it a separate issue if you want to close this as it is 🌸

**Comment by camelPhonso** [comment]
> We can make a separate issue for the renaming the util functions? Re the modal window, it's up to you. We can make it a separate issue if you want to close this as it is 🌸

Aye, I reckon we'd best close this as is now and separate that issue out for a smaller isolated PR ✨ 

In that case if you're happy can you give an approval here to unlock merging?

**Review by eliazzo — APPROVED** [review]

**Pull request merged**
