### PR TITLE
style:fixes conversation list overflow

### LINKED ISSUE #140: 🐞 ConversationsList overflow 🐛
# Expected Behaviour

When a user has a long list of conversations active the `ConversationCard`s should scroll on `ConversationsList`

# Current Behaviour

`ConversationsList` is static and forces the page to expand
Screenshot 2024-03-26 at 16 11 35

<hr>

# Failure Information

The code does not fail 💡 it creates the behaviour demonstrated above

## Steps to Reproduce

1. Log in
2. Find an item
3. Create a new conversation by clicking the "Message" button
4. Repeat this until your `/conversations` page displays enough `ConversationCard`s to overflow the page

## Failure Logs

No failure :)

### LINKED ISSUE #161: Last conversation card in conversation list covered by nav bar
# Expected Behaviour

When viewing the conversation list the last card should end above the nav bar.

# Current Behaviour

The last conversation card gets cut off by the navigation bar when viewing the conversation list after resizing the conversation window then pressing the 'back' button. 
kindly-message-issue

## Steps to Reproduce

1. Login
2. Navigate to messages
3. Create lots of conversations
4. Resize window until layout changes to mobile version
5. Click the 'back' button
6. Scroll to end of conversation list

### PR DESCRIPTION
**Pull request by Edga380**
closes #140 
closes #161 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review on my code
- [ ] I have made corresponding changes to the documentation (if any were needed)
- [x] My changes generate no new warnings or errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and previously existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Description

**Closes #140
Adds overflow to the conversation list.

### Files changed

Added (overflow-y-auto) <div className='m-4 overflow-y-auto'> to ConversationsList.tsx file.

### UI changes

Screenshot from 2024-04-09 13-42-44

### Changes to Documentation

None

# Tests

None

### CODE REVIEW

**Comment by fintonius** [comment]
Hi @camelPhonso I'll have a go at that now. We weren't sure if #161 should be a separate issue or not but thought it was worth doing to get some practice creating an issue :)

**Comment by camelPhonso** [comment]
> Hi @camelPhonso I'll have a go at that now. We weren't sure if #161 should be a separate issue or not but thought it was worth doing to get some practice creating an issue :)

You thought well 👌 but it is a small enough change to sort here. Just reference that issue on your commits when you push new changes to this branch :)

**Comment by fintonius** [comment]
> > You thought well 👌 but it is a small enough change to sort here. Just reference that issue on your commits when you push new changes to this branch :)

thanks! I've found the problem, it's being caused by some of the styles being applied to different media breakpoints in the messaging-styles.css file. I've tried a few different ways to fix it but they end up affecting the rest of the layout in negative ways. I'll take another look at it later in the week, hopefully can figure out the solution

**Comment by camelPhonso** [comment]
@Edga380 can you please pull dev again and merge into your branch? We've actioned some changes that should fix the deployment issue you're having on this PR

**Comment by Edga380** [comment]
@camelPhonso I just did that. Should I do an empty commit now and push it?

**Comment by Edga380** [comment]
@camelPhonso Okay so I just did that and it looks like everything is okay. Thanks for your help I learned something new today :)

**Review by nichgalzin — CHANGES_REQUESTED** [review]
Two things:
   - The mobile version of has extra space around the mobile nav bar. See here:
Screenshot 2024-04-23 at 11 45 56
The height of the these containers are controlled by a class in messaging styles and will need to be adjusted. I've been magic numbering to get this to work, but maybe another approach will be needed. Let me know if you need some more clarification on this.
- Back button is in the middle of the screen now, although we will be changing this, might as well fix this for the time present.

**Review by ShaughnAnderson94 — APPROVED** [review]
we all love this

**Review by nichgalzin — APPROVED** [review]
Thanks for fixing this!

**Pull request merged**
