### PR TITLE
created link button to new item

### PR DESCRIPTION
**Pull request by aaleksa**
# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review on my code
- [ ] I have made corresponding changes to the documentation (if any were needed)
- [ ] My changes generate no new warnings or errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and previously existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Description

**Relates #[issue number] <u>OR</u> Closes #[issue number]**  
Include here a short description of what behaviour this Pull Request introduces.
Outline any new dependencies introduced.

### Files changed

Include one to two lines on the necessary changes to each file.
1. app/(dashboard)/add-item/page.tsx
           Added itemId to the path in  router redirect
2. app/(dashboard)/add-item/success/page.tsx
          Added Button <ButtonGoToItem>
3. components/buttons/ButtonGoToItem.tsx
        ButtonGoToItem implementation
4. supabase/models/insertRow.ts
      Return created item record on api call  "supabase.from(table).insert(InsertValues).select();" to create new item

### UI changes

If this PR includes changes to the UI include a **screengrab** of the alterations in review.

### Changes to Documentation

Include an outline of why Documentation needed to be updated with this PR

# Tests

Include a description of any tests added - if none have been added explain why.

### CODE REVIEW

**Comment by aaleksa** [comment]
image
Added new button, 'GO TO YOUR ITEM'

**Review by camelPhonso — CHANGES_REQUESTED** [review]
Thanks @aaleksa - your implementation is working brilliantly 👍 but I'm requesting a few changes that should help us clean up the code base a little.

**Comment by camelPhonso** [comment]
Relates #192 

Just explicitly linking to Issue for traceability

**Comment by camelPhonso** [comment]
Hi @aaleksa can you just confirm that you are still monitoring this PR?

**Comment by camelPhonso** [comment]
Closing this PR as it's been stale and the issue is up for re-assignment

**Pull request closed without merging**
